CREATE TABLE tbUsuario (
cod_usuario int primary key,
nome_usuario varchar(50) not null,
sobrenome_usuario varchar(50) not null,
email_usuario varchar(225) not null unique,
senha_usuario varchar(225) not null,
estado_usuario varchar(50) not null
);

insert into tbUsuario(cod_usuario, nome_usuario, sobrenome_usuario, email_usuario, senha_usuario, estado_usuario)
values
('482', 'Ana', 'Santos', 'ana.santos@email.com', 'rT3h6gH2', 'São Paulo'),
('530', 'Arthur', 'Oliveira', 'arthur.oliveira@email.com', 'j3bGpX8w', 'Rio de Janeiro'),
('762', 'Alice', 'Martins', 'alice.martins@email.com', 'tU5yWx9Z', 'Minas Gerais'),
('899', 'Beatriz', 'Silva', 'beatriz.silva@email.com', 'kL2jE4nF', 'Bahia'),
('612', 'Bruno', 'Costa', 'bruno.costa@email.com', 'yA1lQ5jT', 'Pernambuco'),
('975', 'Bianca', 'Pereira', 'bianca.pereira@email.com', 'wS7hR9zM', 'Ceará'),
('435', 'Carla', 'Santos', 'carla.santos@email.com', 'oX2iJ6vD', 'Paraná'),
('214', 'Carlos', 'Oliveira', 'carlos.oliveira@email.com', 'sD4fT9kN', 'Santa Catarina'),
('303', 'Caio', 'Martins', 'caio.martins@email.com', 'vW8uL0dJ', 'Espírito Santo'),
('748', 'Daniela', 'Silva', 'daniela.silva@email.com', 'aR7pM5bX', 'Goiás'),
('192', 'Diego', 'Costa', 'diego.costa@email.com', 'kF2oV9zP', 'Maranhão'),
('903', 'Danilo', 'Pereira', 'danilo.pereira@email.com', 'eN4uJ3xR', 'Rio Grande do Sul'),
('836', 'Eduardo', 'Santos', 'eduardo.santos@email.com', 'iT5oK7dF', 'Tocantins'),
('652', 'Ester', 'Oliveira', 'ester.oliveira@email.com', 'uD9pF8kG', 'Acre'),
('124', 'Elaine', 'Martins', 'elaine.martins@email.com', 'rX6zV3sB', 'Rondônia'),
('967', 'Fernanda', 'Silva', 'fernanda.silva@email.com', 'tL3bW9yA', 'Amazonas'),
('504', 'Felipe', 'Costa', 'felipe.costa@email.com', 'vJ8dK7hE', 'Alagoas'),
('340', 'Fábio', 'Pereira', 'fabio.pereira@email.com', 'mR2hG6yL', 'Mato Grosso do Sul'),
('824', 'Gabriela', 'Santos', 'gabriela.santos@email.com', 'zF3kJ5pT', 'Piauí'),
('731', 'Gustavo', 'Oliveira', 'gustavo.oliveira@email.com', 'sM4iB9uD', 'Distrito Federal'),
('256', 'Guilherme', 'Martins', 'guilherme.martins@email.com', 'pR2kF9oN', 'São Paulo'),
('547', 'Helena', 'Silva', 'helena.silva@email.com', 'fR6iJ3lM', 'Rio de Janeiro'),
('381', 'Henrique', 'Costa', 'henrique.costa@email.com', 'lT7sJ2oQ', 'Minas Gerais'),
('964', 'Heloísa', 'Pereira', 'heloisa.pereira@email.com', 'oX5tN9fK', 'Bahia'),
('223', 'Isabel', 'Santos', 'isabel.santos@email.com', 'vK2wH7pT', 'Pernambuco'),
('654', 'Igor', 'Oliveira', 'igor.oliveira@email.com', 'sP9jF5lN', 'Ceará'),
('871', 'Ingrid', 'Martins', 'ingrid.martins@email.com', 'uX4vZ9oB', 'Paraná'),
('640', 'Julia', 'Silva', 'julia.silva@email.com', 'tB3yG2jN', 'Santa Catarina'),
('372', 'João', 'Costa', 'joao.costa@email.com', 'kF8vM2pT', 'Espírito Santo'),
('587', 'Jessica', 'Pereira', 'jessica.pereira@email.com', 'qR1mD9hL', 'Goiás'),
('104', 'Karen', 'Santos', 'karen.santos@email.com', 'vM7zL4pT', 'Maranhão'),
('930', 'Kevin', 'Oliveira', 'kevin.oliveira@email.com', 'xN2fJ3tW', 'Rio Grande do Sul'),
('755', 'Karina', 'Martins', 'karina.martins@email.com', 'cT9kL1gN', 'Tocantins'),
('618', 'Luana', 'Silva', 'luana.silva@email.com', 'dV8yF2pJ', 'Acre'),
('814', 'Lucas', 'Costa', 'lucas.costa@email.com', 'mR5kQ9wN', 'Rondônia'),
('241', 'Lívia', 'Pereira', 'livia.pereira@email.com', 'aS2gN6fT', 'Amazonas'),
('393', 'Mariana', 'Santos', 'mariana.santos@email.com', 'bX9oL5eD', 'Alagoas'),
('506', 'Matheus', 'Oliveira', 'matheus.oliveira@email.com', 'cF3dM8nQ', 'Mato Grosso do Sul'),
('257', 'Maria', 'Martins', 'maria.martins@email.com', 'yW1iP9gT', 'Piauí'),
('429', 'Natalia', 'Silva', 'natalia.silva@email.com', 'qF6rJ4oN', 'Distrito Federal'),
('718', 'Nelson', 'Costa', 'nelson.costa@email.com', 'sA3iT2zB', 'São Paulo'),
('839', 'Natália', 'Pereira', 'natália.pereira@email.com', 'tX9oH7dL', 'Rio de Janeiro'),
('655', 'Olívia', 'Santos', 'olivia.santos@email.com', 'kG4vZ1pT', 'Minas Gerais'),
('936', 'Otávio', 'Oliveira', 'otavio.oliveira@email.com', 'rW5bP7uD', 'Bahia'),
('117', 'Orlando', 'Martins', 'orlando.martins@email.com', 'vF9tK4yL', 'Pernambuco'),
('398', 'Paula', 'Silva', 'paula.silva@email.com', 'hD2oK8pN', 'Ceará'),
('831', 'Paulo', 'Costa', 'paulo.costa@email.com', 'jW7zQ5lF', 'Paraná'),
('592', 'Priscila', 'Pereira', 'priscila.pereira@email.com', 'sB3uY6iV', 'Santa Catarina'),
('179', 'Quésia', 'Santos', 'quesia.santos@email.com', 'oV4hK9wJ', 'Espírito Santo'),
('754', 'Quirino', 'Oliveira', 'quirino.oliveira@email.com', 'rN2vT8iF', 'Goiás'),
('805', 'Quitéria', 'Martins', 'quitéria.martins@email.com', 'zQ9tY5dL', 'Maranhão'),
('902', 'Renata', 'Silva', 'renata.silva@email.com', 'hX6vP2sD', 'Rio Grande do Sul'),
('221', 'Rodrigo', 'Costa', 'rodrigo.costa@email.com', 'cR4yG7zF', 'Tocantins'),
('365', 'Rafael', 'Pereira', 'rafael.pereira@email.com', 'sJ2hQ9kD', 'Acre'),
('499', 'Sofia', 'Santos', 'sofia.santos@email.com', 'uX5mV3bK', 'Rondônia'),
('760', 'Samuel', 'Oliveira', 'samuel.oliveira@email.com', 'fQ1vP6oB', 'Amazonas'),
('890', 'Sabrina', 'Martins', 'sabrina.martins@email.com', 'rF2yJ7nD', 'Alagoas'),
('321', 'Tatiane', 'Silva', 'tatiane.silva@email.com', 'kX5pL3uQ', 'Mato Grosso do Sul'),
('572', 'Thiago', 'Costa', 'thiago.costa@email.com', 'vT6jN2rM', 'Pernambuco'),
('688', 'Teresa', 'Pereira', 'teresa.pereira@email.com', 'wL4fZ9yT', 'Ceará'),
('110', 'Ulisses', 'Santos', 'ulisses.santos@email.com', 'oN1rP3gL', 'São Paulo'),
('259', 'Ursula', 'Oliveira', 'ursula.oliveira@email.com', 'hF9gV5kM', 'Rio de Janeiro'),
('486', 'Vânia', 'Silva', 'vania.silva@email.com', 'rY3pH9zL', 'Minas Gerais'),
('672', 'Vicente', 'Costa', 'vicente.costa@email.com', 'dT2hQ8vF', 'Goiás'),
('548', 'Vanessa', 'Pereira', 'vanessa.pereira@email.com', 'pL1kN4mT', 'Bahia'),
('736', 'Wagner', 'Santos', 'wagner.santos@email.com', 'tZ8dJ6hR', 'Distrito Federal'),
('480', 'Wallace', 'Oliveira', 'wallace.oliveira@email.com', 'cK9gV2fM', 'São Paulo'),
('151', 'Wellington', 'Martins', 'wellington.martins@email.com', 'nD5kP3tF', 'Pernambuco'),
('901', 'Xênia', 'Santos', 'xenia.santos@email.com', 'pB7tV2mL', 'Rio Grande do Sul'),
('276', 'Xerxes', 'Oliveira', 'xerxes.oliveira@email.com', 'qF3gR1vN', 'Tocantins'),
('582', 'Ximena', 'Martins', 'ximena.martins@email.com', 'fY9bD3sM', 'Alagoas'),
('380', 'Yasmin', 'Silva', 'yasmin.silva@email.com', 'jG7pW2uD', 'Tocantins'),
('469', 'Yuri', 'Costa', 'yuri.costa@email.com', 'xJ5oF7bL', 'Piauí'),
('125', 'Yara', 'Pereira', 'yara.pereira@email.com', 'zP2mV6rQ', 'Rio de Janeiro'),
('908', 'Zélia', 'Santos', 'zelia.santos@email.com', 'oF3kT1vN', 'Tocantins'),
('561', 'Zacarias', 'Oliveira', 'zacarias.oliveira@email.com', 'hM7jL2rP', 'Amazonas'),
('234', 'Zenaide', 'Martins', 'zenaide.martins@email.com', 'cX4vY9qD', 'Minas Gerais');